GET http://localhost:3000/api/auth/profile
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZFVzdWFyaW8iOjUsImlhdCI6MTU3OTMyNDU0NiwiZXhwIjoxNTc5MzQyNTQ2fQ.bdC-v_2zV-1G3uFijQK3A9i4LBNWPSQpTCofiElFKyc; Max-Age=18; Path=/; Expires=Sat, 18 Jan 2020 05:16:04 GMT; HttpOnly; Secure

//
